# 异常处理

异常处理能够使程序处理一些特殊现象，并继续正确的执行。

```cpp
#include <iostream>

using namespace std;

int main(int argc, char const *argv[])
{
    double x, y;
    cin >> x >> y;
    try
    {
        if (y == 0)
        {
            throw -1;
        }
    }
    catch(int ex)
    {
        cout << "Exception: cannot be divided by zero." << endl;
        return ex;
    }
    cout << x / y << endl;
    return 0;
}
```

异常可以嵌套，也就是多重异常。

```cpp
#include <iostream>

using namespace std;

int main(int argc, char const *argv[])
{
    double x, y;
    cin >> x >> y;
    try
    {
        if (y == 0)
        {
            throw -1;
        }
    }
    catch(int ex)
    {
        cout << "Exception: cannot be divided by zero." << endl;
        try
        {
            if (x == 0)
            {
                throw -2;
            }    
        }
        catch(int ex)
        {
            cout << "Exception: It's meaningless to do so." << endl;
            return ex;
        }
        return ex;
    }
    cout << x / y << endl;
    return 0;
}
```

